<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Tipos De Horario_1</name>
   <tag></tag>
   <elementGuidId>8ff9911e-d141-4159-8146-4bb407bf86ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#itemTextLink72</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='itemTextLink72']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d1d17a5a-55b2-4801-8b29-49aef7f3f8d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/HCMCRDVALSTD/www/com.aspsolutions.gwtjforms.GWTJForms/GWTJForms.html?timeout=1800000&amp;cn=com.qmn.form.mnejerpt&amp;war=HCMCRDVALSTD&amp;ubicacion=/mnt/FileSystem1/clientes/APO/HCMCRDVALSTD/GRAF-SRH/hdv/sql/&amp;objeto=rhtiphor&amp;tipo=SQL&amp;titulo=Tipos De Horario&amp;ayuda2=432&amp;impresion=Carta(216x279mm) Vertical 25-10-10-10 Curier-new-normal-10&amp;Plat_Cod=4&amp;Ind_Web=S&amp;Dir_Sal=/salidas/hcmcrdval/&amp;Dir_Prt=txt&amp;seguridad=63241215&amp;QRX4=aa</value>
      <webElementGuid>1a102423-91e0-41ec-8f78-d874fad5a2a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>formas</value>
      <webElementGuid>13df2388-d39b-4787-a479-b4cabca3eeab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>clickOnLink('72', '/HCMCRDVALSTD/www/com.aspsolutions.gwtjforms.GWTJForms/GWTJForms.html?timeout=1800000&amp;cn=com.qmn.form.mnejerpt&amp;war=HCMCRDVALSTD&amp;ubicacion=/mnt/FileSystem1/clientes/APO/HCMCRDVALSTD/GRAF-SRH/hdv/sql/&amp;objeto=rhtiphor&amp;tipo=SQL&amp;titulo=Tipos De Horario&amp;ayuda2=432&amp;impresion=Carta(216x279mm) Vertical 25-10-10-10 Curier-new-normal-10&amp;Plat_Cod=4&amp;Ind_Web=S&amp;Dir_Sal=/salidas/hcmcrdval/&amp;Dir_Prt=txt&amp;seguridad=63241215&amp;QRX4=aa','hdv0207','formas');return false;</value>
      <webElementGuid>e8991b20-c20b-4f93-b34a-b3d1990463a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>itemTextLink72</value>
      <webElementGuid>aff252ad-34bc-4ef0-beaf-1b87d712f64d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tipos De Horario</value>
      <webElementGuid>3a68cd9e-b587-473f-92c4-3e56035349e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;itemTextLink72&quot;)</value>
      <webElementGuid>ddf1e98d-ab2b-43fa-9ef4-3b3f5b0d39ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/VERSION_74/3.Modulo_Hojas_de_Vida/Page_Softland HCM/iframe_concat(id(, , left, , )iframe1)_menu</value>
      <webElementGuid>1a4c3ce6-c69e-4158-9b61-8b975123c3a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='itemTextLink72']</value>
      <webElementGuid>eaea41e8-ce76-4861-a435-f204201978ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='item72']/table/tbody/tr/td[4]/a</value>
      <webElementGuid>ccbc5a7a-4514-4d90-a2c1-7ac8b95f17d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Tipos De Horario')]</value>
      <webElementGuid>b4d92a91-4515-4e2a-81c6-debae11b6632</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Entidades Y Coberturas'])[1]/following::a[2]</value>
      <webElementGuid>ad1f7b83-a299-446b-a8a8-6edc588a65a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipos De Nomina'])[1]/following::a[4]</value>
      <webElementGuid>5b0b5e15-9cf2-4dc6-b227-4bcff4721166</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DE DATOS PERSONALES DE EMPLEADOS'])[1]/preceding::a[3]</value>
      <webElementGuid>c0f6bcd7-f1bf-472c-8f3f-23a75cd46a5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DE DATOS LABORALES DE EMPLEADOS'])[1]/preceding::a[24]</value>
      <webElementGuid>d3ddd2ff-b592-4176-8a15-5c4b0deeaf8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tipos De Horario']/parent::*</value>
      <webElementGuid>92985a7c-0ccb-406f-98f0-2e763d576905</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/HCMCRDVALSTD/www/com.aspsolutions.gwtjforms.GWTJForms/GWTJForms.html?timeout=1800000&amp;cn=com.qmn.form.mnejerpt&amp;war=HCMCRDVALSTD&amp;ubicacion=/mnt/FileSystem1/clientes/APO/HCMCRDVALSTD/GRAF-SRH/hdv/sql/&amp;objeto=rhtiphor&amp;tipo=SQL&amp;titulo=Tipos De Horario&amp;ayuda2=432&amp;impresion=Carta(216x279mm) Vertical 25-10-10-10 Curier-new-normal-10&amp;Plat_Cod=4&amp;Ind_Web=S&amp;Dir_Sal=/salidas/hcmcrdval/&amp;Dir_Prt=txt&amp;seguridad=63241215&amp;QRX4=aa')])[2]</value>
      <webElementGuid>a652f4aa-80a2-46ae-b311-c7358631d469</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[74]/table/tbody/tr/td[4]/a</value>
      <webElementGuid>d9f4f673-23b4-450c-8ea7-61790f3d540d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/HCMCRDVALSTD/www/com.aspsolutions.gwtjforms.GWTJForms/GWTJForms.html?timeout=1800000&amp;cn=com.qmn.form.mnejerpt&amp;war=HCMCRDVALSTD&amp;ubicacion=/mnt/FileSystem1/clientes/APO/HCMCRDVALSTD/GRAF-SRH/hdv/sql/&amp;objeto=rhtiphor&amp;tipo=SQL&amp;titulo=Tipos De Horario&amp;ayuda2=432&amp;impresion=Carta(216x279mm) Vertical 25-10-10-10 Curier-new-normal-10&amp;Plat_Cod=4&amp;Ind_Web=S&amp;Dir_Sal=/salidas/hcmcrdval/&amp;Dir_Prt=txt&amp;seguridad=63241215&amp;QRX4=aa' and @id = 'itemTextLink72' and (text() = 'Tipos De Horario' or . = 'Tipos De Horario')]</value>
      <webElementGuid>a0ed0e0f-9db4-4878-b436-f40d695ac868</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
