<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Tipos De Horario</name>
   <tag></tag>
   <elementGuidId>b079219a-d815-4003-91cd-68718b3aecbd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#itemTextLink72</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='itemTextLink72']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>efe22353-f2de-4b75-8a67-594525bb0bc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/HCMCRDVALSTD/www/com.aspsolutions.gwtjforms.GWTJForms/GWTJForms.html?timeout=1800000&amp;cn=com.qmn.form.mnejerpt&amp;war=HCMCRDVALSTD&amp;ubicacion=/mnt/FileSystem1/clientes/APO/HCMCRDVALSTD/GRAF-SRH/hdv/sql/&amp;objeto=rhtiphor&amp;tipo=SQL&amp;titulo=Tipos De Horario&amp;ayuda2=432&amp;impresion=Carta(216x279mm) Vertical 25-10-10-10 Curier-new-normal-10&amp;Plat_Cod=4&amp;Ind_Web=S&amp;Dir_Sal=/salidas/hcmcrdval/&amp;Dir_Prt=txt&amp;seguridad=62979872&amp;QRX4=aa</value>
      <webElementGuid>7a979e1c-8f6b-4e03-b5be-c74627f291f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>formas</value>
      <webElementGuid>cad97f65-b510-44f0-8ce1-7d14f1fcda13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>clickOnLink('72', '/HCMCRDVALSTD/www/com.aspsolutions.gwtjforms.GWTJForms/GWTJForms.html?timeout=1800000&amp;cn=com.qmn.form.mnejerpt&amp;war=HCMCRDVALSTD&amp;ubicacion=/mnt/FileSystem1/clientes/APO/HCMCRDVALSTD/GRAF-SRH/hdv/sql/&amp;objeto=rhtiphor&amp;tipo=SQL&amp;titulo=Tipos De Horario&amp;ayuda2=432&amp;impresion=Carta(216x279mm) Vertical 25-10-10-10 Curier-new-normal-10&amp;Plat_Cod=4&amp;Ind_Web=S&amp;Dir_Sal=/salidas/hcmcrdval/&amp;Dir_Prt=txt&amp;seguridad=62979872&amp;QRX4=aa','hdv0207','formas');return false;</value>
      <webElementGuid>c0d963f2-bda0-49b1-8b68-b2ddf497819b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>itemTextLink72</value>
      <webElementGuid>4cbee1d9-7941-4345-be4f-56b71dc90e40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tipos De Horario</value>
      <webElementGuid>133e494b-d8e4-469b-9ee3-bbd821a9704e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;itemTextLink72&quot;)</value>
      <webElementGuid>5a151f94-98a5-483d-9451-8aab6726e249</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/VERSION_74/3.Modulo_Hojas_de_Vida/Page_Softland HCM/iframe_concat(id(, , left, , )iframe1)_menu</value>
      <webElementGuid>daf013b5-3324-40e2-be58-ed4ab6b17892</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='itemTextLink72']</value>
      <webElementGuid>8152a3c4-b237-4202-a3b4-7643b230d45f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='item72']/table/tbody/tr/td[4]/a</value>
      <webElementGuid>e29fea3a-c3b1-47f8-9d82-40a715a354d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Tipos De Horario')]</value>
      <webElementGuid>f1d3bd8d-1903-45c1-8c83-b6859e3b128c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Entidades Y Coberturas'])[1]/following::a[2]</value>
      <webElementGuid>0dda6f61-913d-4b0b-ac6f-c92747df54ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipos De Nomina'])[1]/following::a[4]</value>
      <webElementGuid>4458db2c-1456-4c73-8587-88b53e731a8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DE DATOS PERSONALES DE EMPLEADOS'])[1]/preceding::a[3]</value>
      <webElementGuid>152cbaea-415f-4133-91f8-45c6704d29ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DE DATOS LABORALES DE EMPLEADOS'])[1]/preceding::a[24]</value>
      <webElementGuid>5604f2ee-e1df-40cb-abcf-5c459b0e65ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tipos De Horario']/parent::*</value>
      <webElementGuid>2331fd75-d8f1-4f7d-a48d-056c8c17f886</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/HCMCRDVALSTD/www/com.aspsolutions.gwtjforms.GWTJForms/GWTJForms.html?timeout=1800000&amp;cn=com.qmn.form.mnejerpt&amp;war=HCMCRDVALSTD&amp;ubicacion=/mnt/FileSystem1/clientes/APO/HCMCRDVALSTD/GRAF-SRH/hdv/sql/&amp;objeto=rhtiphor&amp;tipo=SQL&amp;titulo=Tipos De Horario&amp;ayuda2=432&amp;impresion=Carta(216x279mm) Vertical 25-10-10-10 Curier-new-normal-10&amp;Plat_Cod=4&amp;Ind_Web=S&amp;Dir_Sal=/salidas/hcmcrdval/&amp;Dir_Prt=txt&amp;seguridad=62979872&amp;QRX4=aa')])[2]</value>
      <webElementGuid>10a5534e-c2ce-4dcd-8ec3-e4b42194e098</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[74]/table/tbody/tr/td[4]/a</value>
      <webElementGuid>8a8d4817-e76d-4333-810b-e07bce5a37d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/HCMCRDVALSTD/www/com.aspsolutions.gwtjforms.GWTJForms/GWTJForms.html?timeout=1800000&amp;cn=com.qmn.form.mnejerpt&amp;war=HCMCRDVALSTD&amp;ubicacion=/mnt/FileSystem1/clientes/APO/HCMCRDVALSTD/GRAF-SRH/hdv/sql/&amp;objeto=rhtiphor&amp;tipo=SQL&amp;titulo=Tipos De Horario&amp;ayuda2=432&amp;impresion=Carta(216x279mm) Vertical 25-10-10-10 Curier-new-normal-10&amp;Plat_Cod=4&amp;Ind_Web=S&amp;Dir_Sal=/salidas/hcmcrdval/&amp;Dir_Prt=txt&amp;seguridad=62979872&amp;QRX4=aa' and @id = 'itemTextLink72' and (text() = 'Tipos De Horario' or . = 'Tipos De Horario')]</value>
      <webElementGuid>29d18113-2e18-4f99-8805-ad4b98a28436</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
