<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Generar</name>
   <tag></tag>
   <elementGuidId>02fc13f5-13ef-44f0-9b26-8ffa4b2df4e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.default_XButtonText</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='2']/div/div[3]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c6c8d54b-6cdb-4237-94b7-746cc5bb94a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>default_XButtonText</value>
      <webElementGuid>1c732beb-817b-498d-9e46-acb5547e3872</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Generar</value>
      <webElementGuid>420d47e0-8da9-4554-8012-266e51399ff4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;2&quot;)/div[@class=&quot;default_XButton&quot;]/div[@class=&quot;default_XButtonInnerButton&quot;]/div[@class=&quot;default_XButtonText&quot;]</value>
      <webElementGuid>ddb07098-fced-4b90-aedf-0a415ed953cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/VERSION_74/3.Modulo_Hojas_de_Vida/Page_Softland HCM/iframe_concat(id(, , ce, , ))_formas</value>
      <webElementGuid>a289cafa-c4e7-48d3-94e5-56aad7132934</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='2']/div/div[3]/div</value>
      <webElementGuid>d1af08d3-87a2-4ad3-8ce4-421b92eed7d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿Se genera reporte por empleado?'])[1]/following::div[6]</value>
      <webElementGuid>ea2002dd-d0e8-44df-84a4-1c78835305ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Salida:'])[2]/following::div[6]</value>
      <webElementGuid>0ba2f43a-3038-4d92-9467-004c49545e5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancelar'])[1]/preceding::div[9]</value>
      <webElementGuid>300a148f-e1a5-4978-9cb8-8f7ad23766b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Editar'])[1]/preceding::div[20]</value>
      <webElementGuid>0012ecca-8607-492c-9d50-5d5118002aff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Generar']/parent::*</value>
      <webElementGuid>a5bffdc0-8cb1-4e0c-b6e0-f7652c378767</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/div</value>
      <webElementGuid>0fffafe2-820c-4a1a-a0e0-7d11196f99cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Generar' or . = 'Generar')]</value>
      <webElementGuid>6f176f31-dce9-4dfb-bb56-348e54fbdb93</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
