<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , ce, , ))_formas</name>
   <tag></tag>
   <elementGuidId>a61f7d0e-b60e-4f72-97c1-f533ebfcb299</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ce</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='ce']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>53282d6e-5aea-45cb-97c7-24fb53e07b4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ce</value>
      <webElementGuid>0bf432a4-d3fd-43c3-bffc-26ebd2a7b431</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/HCMCRDVALSTD/verClasificacion.do</value>
      <webElementGuid>eb0d4da4-d94a-40d5-90bf-17514c41dde8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>formas</value>
      <webElementGuid>681a9e1c-0e3e-4db4-82f7-7473653a969e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>aa453d4f-bc1b-4db3-aced-4c2e0a9afdb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>848819ee-8120-4582-bca2-7937771351e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>07ada6f1-8ae6-40bc-a4d9-eff3b73a5d08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>edf4e068-95b4-4f8b-b5c4-578cef550b87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ce&quot;)</value>
      <webElementGuid>083b399a-9cc1-46f7-ac7a-f42ef3912f20</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='ce']</value>
      <webElementGuid>77ecf565-ec0e-4124-90fc-9131a94afc75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='center']/iframe</value>
      <webElementGuid>a70d08ae-4696-4589-a14d-e8e7d4e65da8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/iframe</value>
      <webElementGuid>12dbde49-3959-4c81-8427-975b9e38cee3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'ce' and @src = '/HCMCRDVALSTD/verClasificacion.do' and @name = 'formas']</value>
      <webElementGuid>ad803c91-639c-49e3-af73-18cd8c556e7c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
