<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Consulta General Empleado_nodeIcon57</name>
   <tag></tag>
   <elementGuidId>337788e1-5e85-45a9-8d58-8e90427a8b01</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nodeIcon57</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='nodeIcon57']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6c525183-f240-445c-a6e7-5f31994303f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nodeIcon57</value>
      <webElementGuid>7f74c46c-3e03-4cd2-b7bc-0454e77b4c6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nodeIcon57</value>
      <webElementGuid>602dfe20-cb7a-4076-942c-2d2d1da9fc18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/HCMCRDVALSTD/imagenes/arbol/ftv2pnode.gif</value>
      <webElementGuid>8be0c2eb-43ee-469d-9067-f9dd32c4a3af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>931de1c6-d289-4467-b1f5-64752ddd879b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>22</value>
      <webElementGuid>980f125e-93ba-43ba-bf9b-71c90f93a259</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a800db4f-d0cb-4c49-8f9b-64215b3855e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nodeIcon57&quot;)</value>
      <webElementGuid>30a210c2-e2f0-4e88-873f-cbf1b1a1cdb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/VERSION_74/3.Modulo_Hojas_de_Vida/Page_Softland HCM/iframe_concat(id(, , left, , )iframe1)_menu</value>
      <webElementGuid>a4045d45-3b8e-4553-a232-1d478f32a65c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='nodeIcon57']</value>
      <webElementGuid>439f9f2e-28be-4cbf-ae51-337d241b3853</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='folder57']/table/tbody/tr/td/a/img</value>
      <webElementGuid>d80b8c1b-8069-467a-9738-67eed19eba0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[59]/table/tbody/tr/td/a/img</value>
      <webElementGuid>3060b053-78fa-4074-abcd-713062c59847</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@name = 'nodeIcon57' and @id = 'nodeIcon57' and @src = '/HCMCRDVALSTD/imagenes/arbol/ftv2pnode.gif']</value>
      <webElementGuid>f1a2bd31-241d-4b35-8b72-0ed150e6bd2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
