<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ingresar_usuario</name>
   <tag></tag>
   <elementGuidId>5cd3e5d3-3a8f-4b0e-a6a5-9bb3db712269</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#InpUsu</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='InpUsu']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c171ce2e-2198-4554-b1c7-d6f2b27c1b02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>InpUsu</value>
      <webElementGuid>b2c8b4aa-aae5-4334-9a15-f5a34382d586</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>55f7dc66-ce9d-40c3-8077-77f46318e33e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>usuario</value>
      <webElementGuid>6453f1b5-89a8-4a93-95f1-ed5c24855f71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control miclase</value>
      <webElementGuid>95c0f3a9-1568-4350-b5fd-326ee1da742f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Usuario</value>
      <webElementGuid>26e2680c-b23f-4abc-842f-235e5fade6f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>33f4b544-3e5e-44ca-9ca8-ce75cf4fd8f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>this.value = this.value.toUpperCase();</value>
      <webElementGuid>6363fca3-73ff-449e-bc94-4fde6cea685b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;InpUsu&quot;)</value>
      <webElementGuid>a7abded8-a86f-4eaa-98ab-0969d3967a14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='InpUsu']</value>
      <webElementGuid>1f3c21d2-6e0b-4f44-8383-f89d06e42996</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>93b1b2c8-2f7d-482c-a4c5-46a66a03c340</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'InpUsu' and @type = 'text' and @name = 'usuario' and @placeholder = 'Usuario']</value>
      <webElementGuid>622fb1a2-2600-4ac2-a97e-9ce8fe22b176</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
