<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_REPORTES</name>
   <tag></tag>
   <elementGuidId>048eeace-147f-4a73-b315-eab17cfc88f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#itemTextLink54</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='itemTextLink54']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d4099ab7-d1d5-43dd-9b24-d7cfd45804e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:parent.op()</value>
      <webElementGuid>03fbc7e0-6150-4ef0-943d-a4a9cb33024b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>formas</value>
      <webElementGuid>a4afbebc-216b-4b30-9085-554b2cffc34a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>itemTextLink54</value>
      <webElementGuid>3099046f-b299-4e4b-80c9-a98d8f378029</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:clickOnFolder(&quot;54&quot;)</value>
      <webElementGuid>b71d5584-66d8-40e3-aa16-54eb4aaad8e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>REPORTES</value>
      <webElementGuid>aae08518-123c-48de-928d-30ee21e22cb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;itemTextLink54&quot;)</value>
      <webElementGuid>324cd6c9-feee-4a1e-87d4-d4cdc1ae004f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/3.Modulo_Hojas_de_Vida/1.Generar_ReporteSQL_Tipos_de_Horario/Page_Sistema de Recursos Humanos y Nmina/frame_html1frameset1frameset1frameset1frame2_menu</value>
      <webElementGuid>e4ba34d7-2393-4d3d-a3b0-ea4e935498ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='itemTextLink54']</value>
      <webElementGuid>4c36d9c0-09df-4e05-9b58-5f6e6429afbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='folder54']/table/tbody/tr/td[3]/a</value>
      <webElementGuid>16f1626e-b6c5-432e-b77d-e8bb5fd830bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'REPORTES')]</value>
      <webElementGuid>3ef7e5c8-8af1-44dd-b95c-a75ee64a6474</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Polivalencia x Empleado'])[1]/following::a[3]</value>
      <webElementGuid>64cc6a78-ec43-4340-9de6-007de7338d79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Consulta Historico de Contraseñas'])[1]/following::a[5]</value>
      <webElementGuid>36dfe673-0bda-47d1-9c8d-3831348f1215</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Parametros De Reportes'])[1]/preceding::a[2]</value>
      <webElementGuid>ddabee12-2420-4c52-a63b-3323c8acf1a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REPORTES ESTADÍSTICOS'])[1]/preceding::a[5]</value>
      <webElementGuid>7c9f9087-9d95-4bbf-8505-d9a092bd99b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='REPORTES']/parent::*</value>
      <webElementGuid>db92e546-99db-41e5-8901-574c15bfd901</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:parent.op()')])[16]</value>
      <webElementGuid>39ac0902-e0e1-41cb-8e44-97ab887a5450</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[56]/table/tbody/tr/td[3]/a</value>
      <webElementGuid>fb4b2c30-80ff-4f48-9665-572b22d9e6b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:parent.op()' and @id = 'itemTextLink54' and (text() = 'REPORTES' or . = 'REPORTES')]</value>
      <webElementGuid>36251448-9997-4df1-bee1-ffc5d1c8cea8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
