<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>frame_formas</name>
   <tag></tag>
   <elementGuidId>170fea61-e1c9-487d-8305-556f039357aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>frame[name=&quot;formas&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//frame[@name='formas']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>frame</value>
      <webElementGuid>5de29031-87ae-4052-bdfe-d74f23edb331</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/HCMSACEITES/verClasificacion.do</value>
      <webElementGuid>70856b77-82a9-4d82-bdc5-0e052cfaa661</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>formas</value>
      <webElementGuid>3d4a7a40-7321-42ac-9bb7-c24f0a62e724</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>1ab38569-f03c-4602-8dcd-1152a0b1e420</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>bcbc3db6-d077-46af-90f8-74dde0fa4556</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/frameset[1]/frameset[1]/frameset[2]/frame[1]</value>
      <webElementGuid>12365eb8-1da3-4cb4-9639-894ea6255232</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//frame[@name='formas']</value>
      <webElementGuid>166d1e13-4df1-4e91-89c3-e772bfcbf1a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//frameset[2]/frame</value>
      <webElementGuid>a3595ace-abc7-4072-8250-2319b0c2df58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//frame[@src = '/HCMSACEITES/verClasificacion.do' and @name = 'formas']</value>
      <webElementGuid>b9bf7591-26fd-499c-8809-dcf1519f30a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
