<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Generar</name>
   <tag></tag>
   <elementGuidId>2c6fed2d-21b3-4197-a750-c74ac63030c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.default_XButtonText</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='2']/div/div[3]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>30913ed4-42d7-400b-b6c7-c324150433bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>default_XButtonText</value>
      <webElementGuid>601c402b-fafb-4cf6-ac9a-114366681ae1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Generar</value>
      <webElementGuid>44c6f9b2-68bf-4863-a9e3-f2516ae7230f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;2&quot;)/div[@class=&quot;default_XButton&quot;]/div[@class=&quot;default_XButtonInnerButton&quot;]/div[@class=&quot;default_XButtonText&quot;]</value>
      <webElementGuid>4f0432ff-d0e7-439e-a7dd-3d8524eb12ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/VERSION_7018/3.Modulo_Hojas_de_Vida/1.Generar_ReporteSQL_Tipos_de_Horario/Page_Sistema de Recursos Humanos y Nmina/frame_formas</value>
      <webElementGuid>60babe38-6361-4f8e-8f84-4e0227694de2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='2']/div/div[3]/div</value>
      <webElementGuid>240b001f-d740-48d7-b7e1-8da949ba77a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿Se genera reporte por empleado?'])[1]/following::div[6]</value>
      <webElementGuid>2b227bb0-3dc9-41f4-a923-a52fb90a5931</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Salida:'])[2]/following::div[6]</value>
      <webElementGuid>c7350d33-9ecf-4fd0-97d2-1dfaaa90856a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancelar'])[1]/preceding::div[9]</value>
      <webElementGuid>306e53ae-47ec-4aa0-8cc7-6294ce65f923</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Editar'])[1]/preceding::div[20]</value>
      <webElementGuid>c35e9966-b1ff-45f1-a437-a324b40e6405</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Generar']/parent::*</value>
      <webElementGuid>f9ce01be-b1fd-430e-bf76-52f5704379fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/div</value>
      <webElementGuid>eee9cd2a-479e-402d-b7d7-1e609305ab65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Generar' or . = 'Generar')]</value>
      <webElementGuid>c83c0844-ddef-47d5-955c-c366688db429</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
