<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>frame_html1frameset1frameset1frameset1frame2_menu</name>
   <tag></tag>
   <elementGuidId>9bfde74b-295c-4ce4-93d9-04c2b6cffeca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>frame[name=&quot;menu&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//frame[@name='menu']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>frame</value>
      <webElementGuid>625dd551-2adf-452d-9c87-f98f845e9899</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/HCMSACEITES/getMenuModulo.do</value>
      <webElementGuid>d22b220d-e322-494c-832b-328684b1c26b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>menu</value>
      <webElementGuid>edf07363-6072-41c7-a868-66812d89935b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>f3a1f58a-9f81-4f8a-b5b2-4089edd01840</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>61c524cc-dcc4-482a-bc5e-bbe125f3510b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/frameset[1]/frameset[1]/frameset[1]/frame[2]</value>
      <webElementGuid>d3d4955a-a280-42bf-bf17-628234bda7d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//frame[@name='menu']</value>
      <webElementGuid>a778c8b7-8da3-445b-a40c-f023c64f9175</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//frameset/frameset/frame[2]</value>
      <webElementGuid>c55f7d39-c59d-443e-93e7-9cefb06fc429</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//frame[@src = '/HCMSACEITES/getMenuModulo.do' and @name = 'menu']</value>
      <webElementGuid>b2734f68-50a3-41e9-9b17-d3e9aed18e34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
