<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>frame_formas</name>
   <tag></tag>
   <elementGuidId>170fea61-e1c9-487d-8305-556f039357aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>frame[name=&quot;formas&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//frame[@name='formas']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>frame</value>
      <webElementGuid>63b61189-2bd6-42ff-ad95-a8faa5bbcb9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/HCMSACEITES/verClasificacion.do</value>
      <webElementGuid>6f9d1fc3-1ab1-41a3-a721-f60f3758320b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>formas</value>
      <webElementGuid>2a1915a7-86ec-4ee5-bf6e-d8cbb7f42c1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>0f1bccaa-a68e-4533-a369-188329896ef8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>cfe52cdc-2dc8-4ed0-adb3-e5ac741bf9de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/frameset[1]/frameset[1]/frameset[2]/frame[1]</value>
      <webElementGuid>dcac22bd-9356-4580-9bab-92002caaa971</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//frame[@name='formas']</value>
      <webElementGuid>fdb88d91-428e-4277-b4d6-c6f4cb05dc20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//frameset[2]/frame</value>
      <webElementGuid>dc3ddf22-26d5-4621-96f6-cc62bbcc4158</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//frame[@src = '/HCMSACEITES/verClasificacion.do' and @name = 'formas']</value>
      <webElementGuid>2f0ec18b-83ee-4c76-98df-8439728f09ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
