<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Polivalencia x Empleado_nodeIcon54</name>
   <tag></tag>
   <elementGuidId>e8b49421-2d90-463c-8411-e3b2f7415f9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nodeIcon54</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='nodeIcon54']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c51c1cf1-3927-47b3-b73e-c63190431a95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nodeIcon54</value>
      <webElementGuid>346e61d3-5d3f-4ecc-81af-86159289bc01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nodeIcon54</value>
      <webElementGuid>3aaacf53-76d8-489a-bfac-68671d06b754</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/HCMSACEITES/imagenes/arbol/ftv2pnode.gif</value>
      <webElementGuid>d3350380-f6f9-4531-addb-052a816629f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>7e50200d-ab34-410f-95c6-8fdfbbfb34c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>22</value>
      <webElementGuid>33eee762-ac87-466f-accb-a38276fd3d66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a1941191-ec09-4278-bf47-a45c83d1ed1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nodeIcon54&quot;)</value>
      <webElementGuid>246db0e1-c5e0-451f-92f5-f501e39bc981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/VERSION_7018/3.Modulo_Hojas_de_Vida/1.Generar_ReporteSQL_Tipos_de_Horario/Page_Sistema de Recursos Humanos y Nmina/frame_html1frameset1frameset1frameset1frame2_menu</value>
      <webElementGuid>c3582392-3966-480f-8b01-65f6d830f917</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='nodeIcon54']</value>
      <webElementGuid>f3031b98-b677-4b97-97b5-43e154eef61e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='folder54']/table/tbody/tr/td/a/img</value>
      <webElementGuid>613fa2dc-44ef-4bc4-ae34-328018833155</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[56]/table/tbody/tr/td/a/img</value>
      <webElementGuid>ffd7bd12-a88e-484b-aba8-a6f2acdf8613</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@name = 'nodeIcon54' and @id = 'nodeIcon54' and @src = '/HCMSACEITES/imagenes/arbol/ftv2pnode.gif']</value>
      <webElementGuid>8baaac2e-45ff-4fd7-88d0-d63d1af3824c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
