<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Clave_clave</name>
   <tag></tag>
   <elementGuidId>7d94484b-02e9-41ca-9b78-38495396868e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;clave&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='clave']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9a281335-bcde-4b52-ab98-69b30dd352e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>56f7632d-5bba-4eeb-9867-12e494521296</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>clave</value>
      <webElementGuid>b6593eff-bf54-40bd-a223-75924bac2dd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>campo</value>
      <webElementGuid>aa8c7576-4b78-4600-a4c2-e545f29ac7f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>2c7c7725-aea1-4973-ad62-1ad435eace99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/center[1]/form[1]/table[@class=&quot;externa&quot;]/tbody[1]/tr[1]/td[1]/table[@class=&quot;interna&quot;]/tbody[1]/tr[2]/td[2]/input[@class=&quot;campo&quot;]</value>
      <webElementGuid>b3e3b722-21ea-4880-8324-f69c2bc78832</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='clave']</value>
      <webElementGuid>149fbdf2-f60e-4ba6-8572-ce95b60dcd91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/input</value>
      <webElementGuid>41c1c377-9d9b-42e7-9e11-17b3a26bd44a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'clave']</value>
      <webElementGuid>f83c8e75-d9a0-4ad3-a232-a0a504c31b88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
