<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Generar</name>
   <tag></tag>
   <elementGuidId>fdabd9e8-76c5-4b12-8987-721351ac08ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.default_XButtonText</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='2']/div/div[3]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4d245275-41da-4745-9b27-ee842072842e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>default_XButtonText</value>
      <webElementGuid>3b8a295b-3b86-461a-b5a3-151295dfe411</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Generar</value>
      <webElementGuid>36e74192-4836-45ff-aaa7-457b6c50294f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;2&quot;)/div[@class=&quot;default_XButton&quot;]/div[@class=&quot;default_XButtonInnerButton&quot;]/div[@class=&quot;default_XButtonText&quot;]</value>
      <webElementGuid>e1563a71-5c17-410e-b3f1-3618d3020298</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/VERSION_73/3. Hojas_de_Vida/Page_Softland HCM/iframe_formas</value>
      <webElementGuid>c3143dcc-56f9-4f8c-8e25-7d33ef6c09c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='2']/div/div[3]/div</value>
      <webElementGuid>712bad90-b143-44d3-a5b2-a854411f2058</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿Se genera reporte por empleado?'])[1]/following::div[6]</value>
      <webElementGuid>be653fd2-3b15-4023-8912-0c65382f1678</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Salida:'])[2]/following::div[6]</value>
      <webElementGuid>e9066f98-c6e0-4b6d-89fb-4e56cf49abba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancelar'])[1]/preceding::div[9]</value>
      <webElementGuid>59e5dbeb-006b-4a26-920d-51ce6a29b280</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Editar'])[1]/preceding::div[20]</value>
      <webElementGuid>7376734d-db17-4f04-a063-3f276b8b5e13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Generar']/parent::*</value>
      <webElementGuid>6f8e8813-ecfc-4ad9-9821-5e2b7871bfcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/div</value>
      <webElementGuid>da72ab4e-dbdb-4bcf-baec-524a872da530</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Generar' or . = 'Generar')]</value>
      <webElementGuid>60a124c6-aed6-4224-85c8-7de1d0b89bcf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
