<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_formas</name>
   <tag></tag>
   <elementGuidId>86b08363-07a2-4767-ad97-f94a4a20a9d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ce</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='ce']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>a4de01a1-431e-4f40-b843-d4686e286a5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ce</value>
      <webElementGuid>51cd5140-1d35-46e2-ace3-f5cbc895d1be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/Q7SOLINME/verClasificacion.do</value>
      <webElementGuid>3a40431b-daea-4064-9bd2-e187a3e8d46f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>formas</value>
      <webElementGuid>3da43833-00d8-495d-ab5f-eeff7b8dc307</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>dad450e0-5e4f-4afc-a5c8-291d771f5905</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>90f3963e-ab24-4338-9c26-3d17e8bfa005</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c393ab38-1e81-4625-9f9f-40aea1d4799c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>532134e4-637d-4b12-95a1-aeeada3eec18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ce&quot;)</value>
      <webElementGuid>96e28719-2513-4a41-b6f3-ad39e0086b0c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='ce']</value>
      <webElementGuid>b2620ca3-57b4-4c56-801a-bf6165c571e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='center']/iframe</value>
      <webElementGuid>f00f9aeb-87a1-46f6-b96f-9e33d2edc6c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/iframe</value>
      <webElementGuid>af6a200d-29de-4546-8707-163203719e72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'ce' and @src = '/Q7SOLINME/verClasificacion.do' and @name = 'formas']</value>
      <webElementGuid>d208507a-d2c1-4ed4-ad99-06149aa49727</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
