<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Consulta General Empleado_nodeIcon60</name>
   <tag></tag>
   <elementGuidId>f0ca1d84-afef-46bf-8c71-57ba25886c09</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nodeIcon60</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='nodeIcon60']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ef38f7ae-e1d3-4cb7-8908-ba75ea69add3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nodeIcon60</value>
      <webElementGuid>55a44722-4a81-40b2-b86c-70c62ecc0a52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nodeIcon60</value>
      <webElementGuid>b90438ee-df58-460a-8104-7675a32275e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/Q7SOLINME/imagenes/arbol/ftv2pnode.gif</value>
      <webElementGuid>4b3bf45c-9f68-4f67-8748-779092acaa47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>d0ea106a-7e06-47ef-b2ad-36f4764e32fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>22</value>
      <webElementGuid>527b7899-c7e0-4ea7-b351-a62e150ad7fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>43e07fde-a0e7-4cc4-a8fd-caf9068d0380</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nodeIcon60&quot;)</value>
      <webElementGuid>bec886d8-6453-46ea-9f8c-f42b93db36c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/VERSION_73/3. Hojas_de_Vida/Page_Softland HCM/iframe_concat(id(, , left, , )iframe1)_menu</value>
      <webElementGuid>2272a386-ef3e-4b5b-a8ff-afc0642287eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='nodeIcon60']</value>
      <webElementGuid>bd95c852-2586-451b-863c-4e7fae608999</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='folder60']/table/tbody/tr/td/a/img</value>
      <webElementGuid>b5e64a2e-15f9-4f2d-a1b3-af7c84b025ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[62]/table/tbody/tr/td/a/img</value>
      <webElementGuid>f3e4935e-c8e1-45ad-ad31-59aef3ce7f37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@name = 'nodeIcon60' and @id = 'nodeIcon60' and @src = '/Q7SOLINME/imagenes/arbol/ftv2pnode.gif']</value>
      <webElementGuid>dcec6a0d-e8a7-4ec0-a2c7-23577ef2a242</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
