<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ingresar_usuario</name>
   <tag></tag>
   <elementGuidId>4fbe8a8f-b763-43ad-98b3-f54dd83fdb7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#InpUsu</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='InpUsu']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d720e9d9-86f8-41b4-891d-96dace498bed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>InpUsu</value>
      <webElementGuid>450e380f-5584-4f8b-a483-182ca82e69e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c941ff1d-1b0c-4b91-8d73-93f70d276c0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>usuario</value>
      <webElementGuid>d1c7f7ed-b891-45b3-8093-bdf00f81475f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control miclase</value>
      <webElementGuid>abfd5e79-8912-4edb-8b4b-deff13e51d63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Usuario</value>
      <webElementGuid>1962441a-01b1-4954-ad2d-4ec940fb38ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>54f1359e-5421-4aab-bd1f-f19658735f9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>this.value = this.value.toUpperCase();</value>
      <webElementGuid>b68526ae-9da6-41c6-afbd-b88777d3f038</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;InpUsu&quot;)</value>
      <webElementGuid>334138e6-d74c-4880-a609-54678ff73300</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='InpUsu']</value>
      <webElementGuid>7ce86dab-097f-4540-9d4f-c70ca5ab2f80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>a1de0ca3-e163-4d4b-a929-4820027ee648</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'InpUsu' and @type = 'text' and @name = 'usuario' and @placeholder = 'Usuario']</value>
      <webElementGuid>fee50a66-c5be-486a-a39f-0936a0f4a131</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
